### ISSUE TITLE
How do you limit the length of tailwind classes? and make them automatically line feed？

### ISSUE THREAD

**Issue by DsCodeStudio** [TailGrids/tailwind-ui-components#1]
## Before 
![image](https://user-images.githubusercontent.com/61904318/155071268-97506d89-3553-49d7-81c4-f8380001f396.png)
## After
![image](https://user-images.githubusercontent.com/61904318/155071318-10f1e2f1-267f-4ddf-b795-16bfce1f3a18.png)

How do you do it? I've been using it all morning and I haven't even achieved this effect! 😭

**Comment by Musharofchy** [comment]
Hey,
Just use this: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier
Thanks
