### ISSUE TITLE
Documentation for Figma > Tailwind CSS

### ISSUE THREAD

**Issue by barchard** [TailGrids/tailwind-ui-components#10]
Hi, are there any documentation or guides to go from the Tailored Figma designs into the appropriate/correct Tailwind CSS? The Figmas generate plain HTML and CSS instead of the same mark-up as provided by the React/Vue/HTML implementations. 

Thanks

**Comment by Musharofchy** [comment]
There is no generation process or anything, you are just getting HTML/CSS, React and Vue coded version of the design that you can see on figma file.
