### ISSUE TITLE
cdn

### ISSUE THREAD

**Issue by ericxin1982** [TailGrids/tailwind-ui-components#6]
Is it support CDN?
I do not want to build, and I want to use it directly like src script="blahblah.js or css"

Thanks
Eric Xin

**Comment by Musharofchy** [comment]
Yes, it does. You can load assets remotely, no worries!

**Comment by ericxin1982** [comment]
Got it, let me play around, thanks so much!

**Comment by ericxin1982** [comment]
Sorry, how to use it like cdn way, I cannot reach any point within documentation.

**Comment by Vinishbhaskar** [comment]
@ericxin1982 While TailGrids officially doesn't support installation via CDN, you can still utilize TailGrids components in your code without installing any NPM package. 

Include the following lines in your HTML file:

```
<script src="https://cdn.jsdelivr.net/npm/tailgrids@2.1.0/plugin.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/tailgrids@2.1.0/assets/css/tailwind.min.css" rel="stylesheet">
```

However, specific components may not function as expected, particularly in dark modes. For troubleshooting, I think you should refer to the Tailwind official documentation: [Tailwind CSS Dark Mode](https://tailwindcss.com/docs/dark-mode).


**Not recommended for production**; it's just for quickly prototyping components.

**Comment by ericxin1982** [comment]
got it, thanks.
